"""yandex-access-token

Revision ID: cb16935a00e0
Revises: f647a71a8a7b
Create Date: 2024-10-18 21:11:23.220081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb16935a00e0'
down_revision: Union[str, None] = 'f647a71a8a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('yandex_access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'yandex_access_token')
    # ### end Alembic commands ###
