"""refactoring-user-pfrofile

Revision ID: f647a71a8a7b
Revises: f9df10589da7
Create Date: 2024-09-25 13:18:23.652914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f647a71a8a7b'
down_revision: Union[str, None] = 'f9df10589da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userprofile', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('userprofile', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userprofile', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('userprofile', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
