"""extend-user-profile

Revision ID: f9df10589da7
Revises: 0244bbc78c04
Create Date: 2024-09-25 12:42:53.228283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9df10589da7'
down_revision: Union[str, None] = '0244bbc78c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('google_access_token', sa.String(), nullable=True))
    op.add_column('userprofile', sa.Column('email', sa.String(), nullable=True))
    op.add_column('userprofile', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'name')
    op.drop_column('userprofile', 'email')
    op.drop_column('userprofile', 'google_access_token')
    # ### end Alembic commands ###
